# Generated by Django 5.0.6 on 2024-07-11 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsimulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
