# Generated by Django 5.0.6 on 2024-07-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsimulation', '0003_user_delete_utilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password1',
            new_name='password',
        ),
    ]
